# experiment parameter gridconfig.yaml
n_cells: [10, 20, 50, 100, 200]
p_change: [0.01, 0.02, 0.05, 0.1, 0.2]
seeds: 20
method: ['bme', 'rnj0', 'rnj1', 'nj-mid', 'nj-root']
tree_type: ['balanced-ultra', 'unbalanced', 'balanced']
results_dir: benchmark_results